# Generated by Django 5.2.3 on 2025-06-28 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, help_text='Maximum monthly spending limit in euros', max_digits=10, verbose_name='Monthly Limit')),
                ('warning_percentage', models.PositiveIntegerField(default=75, help_text='Percentage of the limit to show yellow alert (e.g. 75)', verbose_name='Warning Percentage')),
                ('critical_percentage', models.PositiveIntegerField(default=90, help_text='Percentage of the limit to show red alert (e.g. 90)', verbose_name='Critical Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
    ]
