# Generated by Django 5.2.3 on 2025-10-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_budget_email_alerts_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='critical_percentage',
            field=models.PositiveIntegerField(default=90, help_text='Percentage of the limit to show red alert (e.g., 90)', verbose_name='Critical Percentage'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='email_alerts_enabled',
            field=models.BooleanField(default=False, help_text='Receive email when the critical percentage is exceeded', verbose_name='Email Alerts'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, help_text='Maximum spending per month in euros', max_digits=10, verbose_name='Monthly Limit'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='warning_percentage',
            field=models.PositiveIntegerField(default=75, help_text='Percentage of the limit to show yellow alert (e.g., 75)', verbose_name='Warning Percentage'),
        ),
    ]
